exclude: '.git'
default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
        args: ['-d relaxed']

  - repo: https://github.com/psf/black
    rev: 21.5b1
    hooks:
      - id: black

  - repo: https://github.com/timothycrosley/isort
    rev: 5.8.0
    hooks:
      - id: isort

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: ['--config=setup.cfg']
        additional_dependencies: [flake8-isort, flake8-docstrings]

  - repo: https://github.com/kynan/nbstripout
    rev: 0.3.9
    hooks:
    - id: nbstripout
      args: ["--keep-output"]

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.1.1
    hooks:
      - id: nbqa-isort
      - id: nbqa-black
      - id: nbqa-flake8

  - repo: https://github.com/snakemake/snakefmt
    rev: v0.6.0
    hooks:
      - id: snakefmt
