name: sensecity-africa
channels:
  - conda-forge
  - bioconda
dependencies:
  - python-dotenv>=0.5.1
  - python=3.9
  - pip
  - pip:
      - exif
  - ipykernel
  - contextily
  - geopandas
  - osmnx>=1
  - pillow
  - snakemake
